name : DST

on: 
  workflow_dispatch:

env: 
    A: 25
    B: 10
jobs:

  job1:
    if: ${{ env.A == 25 }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Affichage de A et B
    
      run: |
            echo "A = ${{env.A}} et  B = ${{env.B}}"
  