name : DST

on: 
  workflow_dispatch:

jobs:

  job1:
    if: (${{ vars.A > 0 }} && ${{ vars.B > 0 }})
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Affichage de A et B
    
      run: |
            echo "A = ${{vars.A}} et  B = ${{vars.B}}"
  