name : DST

on: 
  workflow_dispatch:

jobs:

  job1:
    if: (${{ vars.A > 0 }} && ${{ vars.B > 0 }})
    runs-on: ubuntu-latest
    steps:
    - name: Affichage de A et B
    
      run: |
            echo "A = ${{vars.A}} et  B = ${{vars.B}}"


  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute le script
      run: |
        python app.py ${{vars.A}} ${{vars.B}}