name : DST

on: 
  workflow_dispatch:

env: 
    A: 25
    B: 10
    DAY_OF_WEEK: Monday
jobs:

  job1:
    if: ${{ needs.build.outputs.A > needs.build.outputs.B }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: A > B
      run: |
            echo "A est supérieur de B"
  