name : DST

on: 
  workflow_dispatch:

env: 
    A: 25
    B: 10

jobs:

  job1:
    if: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: A et B sont Positive
      run: |
            if(${{env.A}} && ${{env.B}} > 0)  {echo "true"}
  