name : DST

on: 
  workflow_dispatch:

env: 
      A: 25
      B: 10
jobs:

  job1:
    if: ${{ vars.A > vars.B}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: A > B
      run: |
            echo "${{ vars.A }} > ${{ vars.B }}"
  